moodle/config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  devise_for :teachers, controllers: {
    registrations: 'teachers/registrations'
  }, path: 'teachers'


  devise_for :students, controllers: {
    registrations: 'students/registrations'
  }, path: 'students'

  namespace :teach do
    resources :courses do
      resources :assignments do
        resources :submissions, only:[:index, :show]
      end
      resources :posts
    end
  end


  namespace :stud do
    resources :courses, only: [ :index, :show ] do
      collection do
        get :select
        get :upcoming_assignments
        get :progress_bar
        get :fetch_posts
        post :enroll
        delete :unenroll
      end
      resources :assignments, only: [ :index, :show] do
        resources :submissions, only: [ :index, :show, :new, :create ]
      end
      end

end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

moodle/app/views/layouts/_navbar.html.haml
:ruby
  active_devise = (current_teacher || current_student)
  navbar_class = active_devise.class == Teacher ? 'bg-dark navbar-dark' : active_devise.class == Student ? 'navbar-dark bg-primary':'navbar-dark bg-info'

%nav.navbar.navbar-expand-lg{class: navbar_class}
  %a.navbar-brand{:href => "#"} Classroom
  %ul.navbar-nav
    - if active_devise
      %span.badge.rounded-pill.bg-warning.text-dark= content_for :login_as,("As #{active_devise.class.name}")
      = render "layouts/navbars/#{active_devise.class.name.underscore}"
    - else
      %li.nav-item
        = link_to "Sign in as teacher", new_teacher_session_path, class: "nav-link"
      %li.nav-item
        = link_to "Sign in as student", new_student_session_path, class: "nav-link"

moodle/app/views/layouts/application.html.haml
!!!
%html
  %head

    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Moodle"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/manifest.json", :rel => "manifest"}/
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    %link{:rel=>"stylesheet", :href=>"https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"}
    = javascript_importmap_tags
  %body

    = render ("layouts/navbar")

    = yield