moodle/config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  devise_for :teachers, controllers: {
    registrations: 'teachers/registrations'
  }, path: 'teachers'


  devise_for :students, controllers: {
    registrations: 'students/registrations'
  }, path: 'students'

  namespace :teach do
    resources :courses do
      resources :assignments do
        resources :submissions, only:[:index, :show]
      end
      resources :posts
    end
  end


  namespace :stud do
    resources :courses, only: [ :index, :show ] do
      collection do
        get :select
        get :upcoming_assignments
        get :progress_bar
        get :fetch_posts
        post :enroll
        delete :unenroll
      end
      resources :assignments, only: [ :index, :show] do
        resources :submissions, only: [ :index, :show, :new, :create ]
      end
      end

end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

moodle/app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :student
  belongs_to :assignment
  validates :student_id, uniqueness: { scope: :assignment_id}
  has_one_attached :file, dependent: :destroy
  validates :file, presence: true,allow_nil:false
  validates :title, presence: true, allow_blank:true
end

moodle/app/controllers/stud/application_controller.rb
class ApplicationController < ::ApplicationController
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_student!
  active_devise = current_student || current_teacher

end

moodle/app/controllers/stud/assignments_controller.rb
class Stud::AssignmentsController < ApplicationController
  before_action :set_assignment, only: %i[ show]
  before_action :set_course
  before_action :check_enrollment


  # GET /assignments or /assignments.json
  def index
    @assignments = @course.assignments.all
  end

  # GET /assignments/1 or /assignments/1.json
  def show
    @student = current_student
    @assignment = Assignment.find(params[:id])
    @is_submitted = @student.submissions.exists?(assignment_id: @assignment.id)
    @is_deadline_finished = @assignment.deadline < Time.now
  end
    # Use callbacks to share common setup or constraints between actions.
  def set_assignment
    @course = Course.find(params[:course_id ])
    @assignment = @course.assignments.find(params[:id])
  end
  private
  def set_course
    @course = Course.find(params[:course_id ])
  end

    # Only allow a list of trusted parameters through.
    def assignment_params
      params.require(:assignment).permit(:title, :content, :deadline, :course_id)
    end
  def check_enrollment
    unless current_student.courses.include?(@course)
      redirect_to select_stud_courses_path, notice: "enroll in this course to get access to its materials !"
    end
  end
end

moodle/app/controllers/stud/courses_controller.rb
# app/controllers/teach/courses_controller.rb
class Stud::CoursesController < ApplicationController
  before_action :set_course, only: %i[ show]

  # GET /teach/courses or /teach/courses.json
  def index
      @courses = current_student.courses.all
  end
  def progress_bar
    @total= 0.0
    @submitted =0.0
    courses = current_student.courses
    courses.each do |course|
      course.assignments.each do |assignment|
        if current_student.submissions.exists?(assignment_id: assignment.id)
          @submitted+=1
        end
        @total+=1
      end
    end
    begin
      @progress = ((@submitted/@total) *100).round
    rescue FloatDomainError
      @progress = 0
    end
  end
  def upcoming_assignments
    @assignments =[]
    courses = current_student.courses
    courses.each do |course|
      course.assignments.each do |assignment|
        if !current_student.submissions.exists?(assignment_id: assignment.id) &&
          assignment.deadline > Time.current
          @assignments << assignment
        end
      end
    end
  end
  def fetch_posts
    student_courses = current_student.courses
    courses_with_posts = student_courses.includes(:posts)
    all_posts = []
    courses_with_posts.each do |course|
      all_posts.concat(course.posts)
    end
    @posts = all_posts
  end

  def show

  end
  def select
    @student = current_student
    all_courses = Course.all
    student_courses = @student.courses
    @courses = []
    all_courses.each do |course|
      unless student_courses.include?(course)
        @courses.append(course)
      end
    end
  end
  def enroll
    @course = Course.find(params[:course_id])
    current_student.courses << (@course)
    respond_to do |format|
        format.html { redirect_to select_stud_courses_path, notice: "you were successfully enrolled " }
      end
  end
  def unenroll
    @course = Course.find(params[:course_id])
    current_student.courses.delete(@course)
    respond_to do |format|
      format.html { redirect_to stud_courses_path, notice: "you were unenrolled from this course ." }
    end
  end
  # PATCH/PUT /teach/courses/1 or /teach/courses/1.json
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:student).permit(:course_ids[])
  end
end

moodle/app/controllers/stud/submissions_controller.rb
class Stud::SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[ show]
  before_action :set_student, only: %i[new show ]
  before_action :set_assignment, only: %i[new show  ]
  before_action :set_course, only: %i[new show  ]
  def index
    @assignment = Assignment.find(params[:assignment_id])
    @submissions=@assignment.submissions.where(student_id: current_student.id)
  end


  def show
    @course=Course.find(params[:course_id])
    @assignment = @course.assignments.find(params[:assignment_id])
    @submission=@assignment.submissions.where(student_id: current_student.id)
  end

  # GET /submissions/new
  def new
    @course = Course.find(params[:course_id])
    @assignment = @course.assignments.find(params[:assignment_id])
    @submission = @assignment.submissions.build
  end


  # POST /submissions or /submissions.json
  def create
    @course = Course.find(params[:course_id])
    @assignment = @course.assignments.find(params[:assignment_id])
    @submission = @assignment.submissions.build(submission_params)
    @submission.student_id = current_student.id

    respond_to do |format|
      if @submission.save
        format.html { redirect_to stud_course_assignment_submission_path(@course, @assignment, @submission), notice: "Submission was successfully created." }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /submissions/1 or /submissions/1.json

  # DELETE /submissions/1 or /submissions/1.json
  private
    # Use callbacks to share common setup or constraints between actions.
  def set_submission
    @submission = current_student.submissions.find_by(assignment_id: params[:assignment_id])
  end

  def set_student
    @student=current_student
  end
  def set_assignment
    @assignment = Assignment.find(params[:assignment_id])
  end
  def set_course
    @course=Course.find(params[:course_id])
  end

    # Only allow a list of trusted parameters through.
    def submission_params
      params.require(:submission).permit(:title,:file)
    end


end

moodle/app/controllers/teach/submissions_controller.rb
class Teach::SubmissionsController < ApplicationController
  def index
    @assignment = Assignment.find(params[:assignment_id])
    @submissions=@assignment.submissions.all
    @count = @submissions.count
  end


  def show
    @course=Course.find(params[:course_id])
    @assignment = @course.assignments.find(params[:assignment_id])
    @submission=@assignment.submissions.find(:id)
  end

end

moodle/app/helpers/submissions_helper.rb
module SubmissionsHelper
end

moodle/app/views/stud/submissions/_attachment.html.erb
<% if submission.file.attached? %>
  <%= link_to submission.file.filename, url_for(submission.file) %>
<% end %>

moodle/app/views/stud/submissions/_form.html.erb
<%= form_with(model: [ :stud, @course,@assignment, submission ]) do |form| %>
  <% if submission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>
      <ul>
        <% submission.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :file, style: "display: block" %>
    <%= form.file_field :file %>
  </div>

  <div>
   <%= form.submit%>
  </div>
<% end %>

moodle/app/views/stud/submissions/_submission.html.erb
<div id="<%= dom_id submission %>">
  <p>
    <strong>Title: </strong>
    <%= submission.title %>
    <strong>submitted at :</strong>
    <%= submission.created_at %>
    <%= render "attachment", submission:submission %>
  </p>
</div>

moodle/app/views/stud/submissions/edit.html.erb
<% content_for :title, "Editing submission" %>

<h1>Editing submission</h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <%= link_to "Show this submission", @submission %> |
  <%= link_to "Back to submissions", submissions_path %>
</div>

moodle/app/views/stud/submissions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Submissions" %>

<h1>Submissions</h1>

<div id="submissions">
  <% @submissions.each do |submission| %>
    <%= render submission %>
    <p>
      <%= link_to "back to  assignment", stud_course_assignment_path(@assignment.course_id,@assignment)%>
    </p>
  <% end %>
</div>

moodle/app/views/stud/submissions/new.html.erb
<% content_for :title, "New submission" %>

<h1>New submission</h1>

<%= render "form", submission:@submission %>

<br>

moodle/app/views/stud/submissions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @submission %>
<div>
  <%= link_to "Back to assignment", stud_course_assignment_path(@course,@assignment)%>
</div>