moodle/config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  devise_for :teachers, controllers: {
    registrations: 'teachers/registrations'
  }, path: 'teachers'


  devise_for :students, controllers: {
    registrations: 'students/registrations'
  }, path: 'students'

  namespace :teach do
    resources :courses do
      resources :assignments do
        resources :submissions, only:[:index, :show]
      end
      resources :posts
    end
  end


  namespace :stud do
    resources :courses, only: [ :index, :show ] do
      collection do
        get :select
        get :upcoming_assignments
        get :progress_bar
        get :fetch_posts
        post :enroll
        delete :unenroll
      end
      resources :assignments, only: [ :index, :show] do
        resources :submissions, only: [ :index, :show, :new, :create ]
      end
      end

end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

moodle/app/views/layouts/navbars/_student.html.haml
%ul.navbar-nav
  - if current_student
    %li.nav-item
      =link_to "Courses",stud_courses_path, class:"nav-link"
    %li.nav-item
      = link_to "Posts", fetch_posts_stud_courses_path, class:"nav-link"
    %li.nav-item
      =link_to "Upcoming assignments",upcoming_assignments_stud_courses_path, class:"nav-link"
    %li.nav-item
      = link_to "your progress",progress_bar_stud_courses_path, class:"nav-link"
    %li.nav-item
      =link_to "Enroll in new courses",select_stud_courses_path, class:"nav-link"
    %li.nav-item
      = link_to "Sign out", destroy_student_session_path,data: { turbo_method: :delete},  class: "nav-link"

moodle/app/views/layouts/navbars/_teacher.html.haml
%ul.navbar-nav
  - if current_teacher
    %li.nav-item
      = link_to "courses",teach_courses_path, class:"nav-link"
    %li.nav-item
      = link_to "new course",new_teach_course_path, class:"nav-link"
    %li.nav-item
      = link_to "Sign out", destroy_teacher_session_path,data: { turbo_method: :delete},  class: "nav-link"